<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '联系我们';
$typeArr[3] = '新闻中心';
$typeArr[4] = '成功案例';
$typeArr[5] = '荣誉资质';
$typeArr[6] = 'banner';
$typeArr[7] = '新闻资讯';
$typeArr[8] = '问题解答';
$typeArr[9] = '合作伙伴';
$typeArr[10] = '产品代理';
$typeArr[11] = '主营业务';
$typeArr[12] = '网站地图';
$typeArr[13] = '弱电安防';
$typeArr[14] = '系统集成';
$typeArr[15] = '安防监控';
$typeArr[16] = '电子围栏';
$typeArr[17] = 'IT外包';
$typeArr[18] = '弱电安防';
$typeArr[19] = '系统集成';
$typeArr[20] = '程序开发';
?>