<li>
        <div class="anpic"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]" width="239" height="183"/></a></div>
        <span><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></span>
        <p>[field:description function="cn_substr(@me,140)"/]....</p>
        <div class="al_b"><a href="[field:arcurl/]" title="[field:title/]"><img src="/skin/images/hx_21.jpg" width="30" height="28" alt="" /></a></div>
      </li>