<li>
        <div class="khpic"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]" width="236" height="180"/></a></div>
        <div class="khjz_cr"> <span><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></span>
          <p>[field:description function="cn_substr(@me,340)"/]......</p>
          <div class="khjz_b"><a href="[field:arcurl/]" title="[field:title/]"><img src="/skin/images/hx_45.jpg" width="80" height="21" alt="" /></a></div>
        </div>
      </li>