<?php
$z[0]=Array("arcurl","",42,57);
$z[1]=Array("title","",66,80);
$z[2]=Array("litpic","",92,107);
$z[3]=Array("title","",115,129);
$z[4]=Array("title","",138,152);
$z[5]=Array("arcurl","",237,252);
$z[6]=Array("title","",261,275);
$z[7]=Array("title","",277,291);
$z[8]=Array("description","",317,367);
$z[8][4]['function']="cn_substr(@me,340)";
$z[9]=Array("arcurl","",418,433);
$z[10]=Array("title","",442,456);

?>