<?php
$z[0]=Array("arcurl","",31,46);
$z[1]=Array("title","",55,69);
$z[2]=Array("litpic","",81,96);
$z[3]=Array("title","",104,118);
$z[4]=Array("title","",127,141);
$z[5]=Array("arcurl","",224,239);
$z[6]=Array("title","",248,262);
$z[7]=Array("title","",264,278);
$z[8]=Array("description","",302,352);
$z[8][4]['function']="cn_substr(@me,340)";
$z[9]=Array("arcurl","",400,415);
$z[10]=Array("title","",424,438);

?>