<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",144,251);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",260,368);
$z[1][4]['typeid']="12";
$z[2]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",377,484);
$z[2][4]['typeid']="2";
$z[3]=Array("field","(@me==\"\")? @me=\" class='libh linob' \":@me=\"\";",656,751);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n    ",812,1038);
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li class='libh linob'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("arclist","\r\n    <div class=\"slide\"><img src=\"[field:litpic/]\" width=\"1900\" height=\"488\" alt=\"[field:title/]\" title=\"[field:title/]\"/></div>\r\n    ",1106,1285);
$z[5][4]['row']="3";
$z[5][4]['typeid']="6";

?>