<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1238,1274);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1476,1498);
$z[5][4]['name']="position";
$z[6]=Array("channelartlist","\r\n      <h4><a href=\"{dede:field name='typelink'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></h4>\r\n      <div class=\"b4\">\r\n        <ul>\r\n          {dede:channel type='son' }\r\n          <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n      </div>\r\n      ",1512,1965);
$z[6][4]['typeid']="top";
$z[7]=Array("include","",2020,2057);
$z[7][4]['filename']="footer.htm";

?>