<?php
$z[0]=Array("global","",219,245);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1067,1106);
$z[1][4]['filename']="header_m.htm";
$z[2]=Array("field","",1403,1432);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\"></span></li>\r\n        ",1657,1985);
$z[3][4]['type']="son";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[4]=Array("field","",2155,2176);
$z[4][4]['name']="content";
$z[5]=Array("include","",2231,2270);
$z[5][4]['filename']="footer_m.htm";

?>