<?php  exit();
/*
Page: /public_html/index.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-05-05 21:06:10
*/
?>
<?php  exit();
/*
Page: /public_html/index.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-05-05 21:07:13
*/
?>
<?php  exit();
/*
Page: /public_html/index.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-05-05 21:08:00
*/
?>
<?php  exit();
/*
Page: /public_html/index.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-05-05 21:09:03
*/
?>
