<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=mkallct&uppage=0&maxpagesize=50&typeid=0&pageno=8&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM `dede_addonarticle` arc LEFT JOIN `dede_arctype` tp ON arc.typeid=tp.id
  ' at line 4 <br />Error sql: <font color='red'>SELECT tp.typedir,tp.typename,tp.isdefault,tp.defaultname,tp.namerule,tp.namerule2,
                tp.ispart,tp.moresite,tp.siteurl,tp.sitepath,arc.aid,arc.aid AS id,arc.typeid,
                       arc.
                       FROM `dede_addonarticle` arc LEFT JOIN `dede_arctype` tp ON arc.typeid=tp.id
                       WHERE arc.aid IN(27,26,25,24,23,22,21,20) AND arc.arcrank >-1  ORDER BY arc.aid desc </font>
Time2018-05-06 01:35:46
*/
?>
