<?php
$z[0]=Array("arcurl","",42,57);
$z[1]=Array("title","",66,80);
$z[2]=Array("litpic","",92,107);
$z[3]=Array("title","",115,129);
$z[4]=Array("title","",138,152);
$z[5]=Array("arcurl","",215,230);
$z[6]=Array("title","",239,253);
$z[7]=Array("title","",255,269);
$z[8]=Array("description","",293,343);
$z[8][4]['function']="cn_substr(@me,140)";
$z[9]=Array("arcurl","",388,403);
$z[10]=Array("title","",412,426);

?>