<div class="xwzx_pic"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]" width="271" height="168" /></a></div>
      <div class="xwcon" > <span><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></span>
        <p>[field:description function="cn_substr(@me,340)"/]...</p>
        <div class="xwcon_pb"><a href="[field:arcurl/]" title="[field:title/]"><img src="/skin/images/hx_45.jpg" width="80" height="21" alt="" /></a></div>
      </div>