<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",156,263);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",272,380);
$z[1][4]['typeid']="12";
$z[2]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",389,496);
$z[2][4]['typeid']="2";
$z[3]=Array("field","(@me==\"\")? @me=\" class='libh linob' \":@me=\"\";",668,763);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n    ",824,1050);
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li class='libh linob'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("arclist","\r\n    <div class=\"slide\"><img src=\"[field:litpic/]\" width=\"1900\" height=\"488\" alt=\"[field:title/]\" title=\"[field:title/]\"/></div>\r\n    ",1118,1297);
$z[5][4]['row']="3";
$z[5][4]['typeid']="6";

?>