<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1238,1274);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1296,1331);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1401,1423);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n        <dd>\r\n          <div class=\"img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" /></a></div>\r\n          <div class=\"txt\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n        </dd>\r\n        ",1480,1796);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",1875,1941);
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",1987,2024);
$z[9][4]['filename']="footer.htm";

?>